[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nanopore-sequencing-basecaller"
version = "2.0.0"
description = "SquiggleCaller: CTC Connectionist Temporal Classification Basecaller"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
nanopore-sequencing-basecaller = "nanopore_basecaller.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/nanopore-sequencing-basecaller"
Repository = "https://github.com/abusuraihsakhri/nanopore-sequencing-basecaller.git"
